controllers/TransactionController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Transaction;
use app\models\TransactionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;

/**
 * TransactionController implements the CRUD actions for Transaction model.
 */
class TransactionController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['logout','index','create','status-update'],
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                    [
                        'actions' => ['user','all','logout','delete'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['login', 'error','signup'],
                        'allow' => true,
                    ],
                ],
            ],

        ];
    }

    /**
     * Lists all Transaction models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TransactionSearch();
        $queryParams = array_merge([],Yii::$app->request->getQueryParams());
        $queryParams['TransactionSearch']['user_id'] = Yii::$app->user->id;
        $dataProvider = $searchModel->search($queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Transaction models.
     * @return mixed
     */
    public function actionUser($id)
    {
        $searchModel = new TransactionSearch();
        $queryParams = array_merge([],Yii::$app->request->getQueryParams());
        $queryParams['TransactionSearch']['user_id'] = $id;
        $dataProvider = $searchModel->search($queryParams);

        return $this->render('admin', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Transaction models.
     * @return mixed
     */
    public function actionAll()
    {
        $searchModel = new TransactionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('all', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionStatusUpdate($id)
    {
        $model = Transaction::findOne($id);
        $model->getStatus($id);
    }

    /**
     * Creates a new Transaction model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Transaction();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Transaction model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Transaction model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Transaction the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Transaction::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/transaction/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Transaction */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="transaction-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ttl')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/transaction/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TransactionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Транзакции';
$this->params['breadcrumbs'][] = $this->title;

$status = ['в обработке', 'успешно', 'не удачно'];

?>
<div class="transaction-index">

    <?php Pjax::begin(['id' => 'transaction']); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'description',
            'ttl',
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function ($model) use ($status) {
                    switch ($model->status) {
                        case '1':
                            $class = 'success';
                            break;
                        case '0':
                            $class = 'info';
                            break;
                        case '2':
                            $class = 'danger';
                            break;
                        default:
                            $class = 'default';
                    };
                    return Html::tag('span', Html::encode($status[$model->status]), ['class' => 'status label label-'.$class]);
                },
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'status',
                    $status,
                    ['class' => 'form-control', 'prompt' => '']
                ),
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>


</div>

views/transaction/all.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\models\User;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TransactionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Транзакции';
$this->params['breadcrumbs'][] = $this->title;

$status = ['в обработке', 'успешно', 'не удачно'];

?>
<div class="transaction-index">

    <?php Pjax::begin(['id' => 'transaction']); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            [
                'attribute'=>'user_id',
                'value' => function ($model) {
                    return empty($model->user_id) ? '-' : $model->user->username;
                },
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'user_id',
                    User::getArrayUsers(),
                    ['class' => 'form-control', 'prompt' => '']
                ),
            ],
            'description',
            'ttl',
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function ($model) use ($status) {
                    switch ($model->status) {
                        case '1':
                            $class = 'success';
                            break;
                        case '0':
                            $class = 'info';
                            break;
                        case '2':
                            $class = 'danger';
                            break;
                        default:
                            $class = 'default';
                    };
                    return Html::tag('span', Html::encode($status[$model->status]), ['class' => 'status label label-'.$class]);
                },
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'status',
                    $status,
                    ['class' => 'form-control', 'prompt' => '']
                ),
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>


</div>

views/transaction/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Transaction */

$this->title = 'Создать транзакцию';
$this->params['breadcrumbs'][] = ['label' => 'Transactions', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transaction-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/transaction/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TransactionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Транзакции';
$this->params['breadcrumbs'][] = $this->title;

$status = ['в обработке', 'успешно', 'не удачно'];

/* Асинхронный запрос обновление статуса */
$this->registerJs(
    "$(document).on('click', '.refresh_status', function(){
    	status_id = $(this).closest('tr').data('key')
		$.ajax({
            url: '".yii\helpers\Url::toRoute("transaction/status-update")."',
            data: {id: status_id},
            success: function (data){
                //alert(data);
                $.pjax.reload({container:\"#transaction\"});
            },
		});
	});
	"
);
?>
<div class="transaction-index">

    <p>
        <?= Html::a('Создать транзакцию', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(['id' => 'transaction']); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'description',
            'ttl',
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function ($model) use ($status) {
                    switch ($model->status) {
                        case '1':
                            $class = 'success';
                            break;
                        case '0':
                            $class = 'info';
                            break;
                        case '2':
                            $class = 'danger';
                             break;
                        default:
                            $class = 'default';
                    };
                    return Html::tag('span', Html::encode($status[$model->status]), ['class' => 'status label label-'.$class]);
                },
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'status',
                    $status,
                    ['class' => 'form-control', 'prompt' => '']
                ),
            ],
            [
                'format' => 'raw',
                'value' => function ($model) use ($status) {
                    return ($model->status == 0) ? Html::a('', 'javascript:void(0)',
                        ['class' => 'glyphicon glyphicon-refresh refresh_status'],
                        ['title' =>  'Refresh',]) : '';
                }
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>


</div>